{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2ebbcd47",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "German dataset shape: (1000, 25)\n",
      "\n",
      "First few rows of German data:\n",
      "   0   1   2   3   4   5   6   7   8   9   ...  15  16  17  18  19  20  21  \\\n",
      "0   1   6   4  12   5   5   3   4   1  67  ...   0   0   1   0   0   1   0   \n",
      "1   2  48   2  60   1   3   2   2   1  22  ...   0   0   1   0   0   1   0   \n",
      "2   4  12   4  21   1   4   3   3   1  49  ...   0   0   1   0   0   1   0   \n",
      "3   1  42   2  79   1   4   3   4   2  45  ...   0   0   0   0   0   0   0   \n",
      "4   1  24   3  49   1   3   3   4   4  53  ...   1   0   1   0   0   0   0   \n",
      "\n",
      "   22  23  24  \n",
      "0   0   1   1  \n",
      "1   0   1   2  \n",
      "2   1   0   1  \n",
      "3   0   1   1  \n",
      "4   0   1   2  \n",
      "\n",
      "[5 rows x 25 columns]\n",
      "\n",
      "=== Résultats sur données Australian ===\n",
      "Checking license ...\n",
      "Checking license ...\n",
      "cpxchecklic: Exiting with code 1\n",
      "\n",
      "Child process exited with code 1\n",
      "No license found. [0.02 s]\n",
      "CPLEX Error  1016: Community Edition. Problem size limits exceeded. Purchase at http://ibm.biz/error1016.\n",
      "cpxchecklic: Exiting with code 1\n",
      "\n",
      "Child process exited with code 1\n",
      "No license found. [0.02 s]\n",
      "CPLEX Error  1016: Community Edition. Problem size limits exceeded. Purchase at http://ibm.biz/error1016.\n"
     ]
    },
    {
     "ename": "DOcplexLimitsExceeded",
     "evalue": "**** Promotional version. Problem size limits (1000 vars, 1000 consts) exceeded, model has 1406 vars, 718 consts, CPLEX code=1016",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mCplexSolverError\u001b[0m                          Traceback (most recent call last)",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/docplex/mp/cplex_engine.py:2044\u001b[0m, in \u001b[0;36mCplexEngine.solve\u001b[0;34m(self, mdl, parameters, **kwargs)\u001b[0m\n\u001b[1;32m   2043\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m-> 2044\u001b[0m     \u001b[43mcpx\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msolve\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   2046\u001b[0m cpx_status \u001b[38;5;241m=\u001b[39m cpx\u001b[38;5;241m.\u001b[39msolution\u001b[38;5;241m.\u001b[39mget_status()\n",
      "File \u001b[0;32m/Applications/CPLEX_Studio_Community2211/cplex/python/3.9/x86-64_osx/cplex/__init__.py:1312\u001b[0m, in \u001b[0;36mCplex.solve\u001b[0;34m(self, paramsets)\u001b[0m\n\u001b[1;32m   1311\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mobjective\u001b[38;5;241m.\u001b[39mget_num_quadratic_nonzeros() \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[0;32m-> 1312\u001b[0m     \u001b[43m_proc\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mlpopt\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_env\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_e\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_lp\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1313\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n",
      "File \u001b[0;32m/Applications/CPLEX_Studio_Community2211/cplex/python/3.9/x86-64_osx/cplex/_internal/_procedural.py:738\u001b[0m, in \u001b[0;36mlpopt\u001b[0;34m(env, lp)\u001b[0m\n\u001b[1;32m    737\u001b[0m     status \u001b[38;5;241m=\u001b[39m CR\u001b[38;5;241m.\u001b[39mCPXXlpopt(env, lp)\n\u001b[0;32m--> 738\u001b[0m \u001b[43mcheck_status\u001b[49m\u001b[43m(\u001b[49m\u001b[43menv\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mstatus\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/Applications/CPLEX_Studio_Community2211/cplex/python/3.9/x86-64_osx/cplex/_internal/_procedural.py:249\u001b[0m, in \u001b[0;36mStatusChecker.__call__\u001b[0;34m(self, env, status, from_cb)\u001b[0m\n\u001b[1;32m    248\u001b[0m         error_string \u001b[38;5;241m=\u001b[39m geterrorstring(env, status)\n\u001b[0;32m--> 249\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m CplexSolverError(error_string, env, status)\n",
      "\u001b[0;31mCplexSolverError\u001b[0m: CPLEX Error  1016: Community Edition. Problem size limits exceeded. Purchase at http://ibm.biz/error1016.",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mDOcplexLimitsExceeded\u001b[0m                     Traceback (most recent call last)",
      "Input \u001b[0;32mIn [6]\u001b[0m, in \u001b[0;36m<cell line: 75>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     73\u001b[0m \u001b[38;5;66;03m# Test sur les données Australian\u001b[39;00m\n\u001b[1;32m     74\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m=== Résultats sur données Australian ===\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m---> 75\u001b[0m result_australian \u001b[38;5;241m=\u001b[39m \u001b[43mtrain_model\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX_australian\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_australian\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     76\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m result_australian:\n\u001b[1;32m     77\u001b[0m     w, k, obj \u001b[38;5;241m=\u001b[39m result_australian\n",
      "Input \u001b[0;32mIn [6]\u001b[0m, in \u001b[0;36mtrain_model\u001b[0;34m(X, y, h, m_)\u001b[0m\n\u001b[1;32m     40\u001b[0m mdl\u001b[38;5;241m.\u001b[39madd_constraint(mdl\u001b[38;5;241m.\u001b[39msum(w_abs[j] \u001b[38;5;28;01mfor\u001b[39;00m j \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mrange\u001b[39m(m)) \u001b[38;5;241m+\u001b[39m k_abs \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m1\u001b[39m)\n\u001b[1;32m     42\u001b[0m \u001b[38;5;66;03m# --- Résolution ---\u001b[39;00m\n\u001b[0;32m---> 43\u001b[0m solution \u001b[38;5;241m=\u001b[39m \u001b[43mmdl\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msolve\u001b[49m\u001b[43m(\u001b[49m\u001b[43mlog_output\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m)\u001b[49m\n\u001b[1;32m     45\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m solution:\n\u001b[1;32m     46\u001b[0m     w_values \u001b[38;5;241m=\u001b[39m [w[j]\u001b[38;5;241m.\u001b[39msolution_value \u001b[38;5;28;01mfor\u001b[39;00m j \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mrange\u001b[39m(m)]\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/docplex/mp/model.py:4901\u001b[0m, in \u001b[0;36mModel.solve\u001b[0;34m(self, **kwargs)\u001b[0m\n\u001b[1;32m   4898\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39menvironment\u001b[38;5;241m.\u001b[39mhas_cplex:\n\u001b[1;32m   4899\u001b[0m     \u001b[38;5;66;03m# take arg clean flag or this model's\u001b[39;00m\n\u001b[1;32m   4900\u001b[0m     used_clean_before_solve \u001b[38;5;241m=\u001b[39m kwargs\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mclean_before_solve\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mclean_before_solve)\n\u001b[0;32m-> 4901\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_solve_local\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcontext\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mused_clean_before_solve\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mparameter_sets\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;66;03m# lex_timelimits, lex_mipgaps)\u001b[39;00m\n\u001b[1;32m   4902\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m   4903\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mfatal(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mCannot solve model: no CPLEX runtime found.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/docplex/mp/model.py:4949\u001b[0m, in \u001b[0;36mModel._solve_local\u001b[0;34m(self, context, clean_before_solve, parameter_sets)\u001b[0m\n\u001b[1;32m   4947\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m DOcplexException \u001b[38;5;28;01mas\u001b[39;00m docpx_e:  \u001b[38;5;66;03m# pragma: no cover\u001b[39;00m\n\u001b[1;32m   4948\u001b[0m     new_solution \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m-> 4949\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m docpx_e\n\u001b[1;32m   4951\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m   4952\u001b[0m     new_solution \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/docplex/mp/model.py:4938\u001b[0m, in \u001b[0;36mModel._solve_local\u001b[0;34m(self, context, clean_before_solve, parameter_sets)\u001b[0m\n\u001b[1;32m   4935\u001b[0m \u001b[38;5;66;03m# assert used_parameters is not None\u001b[39;00m\n\u001b[1;32m   4936\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_apply_parameters_to_engine(used_parameters)\n\u001b[0;32m-> 4938\u001b[0m new_solution \u001b[38;5;241m=\u001b[39m \u001b[43mself_engine\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msolve\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m   4939\u001b[0m \u001b[43m                                 \u001b[49m\u001b[43mparameters\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mused_parameters\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   4940\u001b[0m \u001b[43m                                 \u001b[49m\u001b[43mclean_before_solve\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mclean_before_solve\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   4941\u001b[0m \u001b[43m                                 \u001b[49m\u001b[43mparameter_sets\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43mparameter_sets\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   4943\u001b[0m \u001b[38;5;66;03m# store solve status as returned by the engine.\u001b[39;00m\n\u001b[1;32m   4944\u001b[0m engine_status \u001b[38;5;241m=\u001b[39m self_engine\u001b[38;5;241m.\u001b[39mget_solve_status()\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/docplex/mp/cplex_engine.py:2080\u001b[0m, in \u001b[0;36mCplexEngine.solve\u001b[0;34m(self, mdl, parameters, **kwargs)\u001b[0m\n\u001b[1;32m   2078\u001b[0m     cpx_status \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1016\u001b[39m\n\u001b[1;32m   2079\u001b[0m     cpx_status_string \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mPromotional version. Problem size limits exceeded., CPLEX code=1016.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m-> 2080\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_model\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfatal_ce_limits\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   2082\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mfix_multiobj_error_1300 \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;241m1300\u001b[39m \u001b[38;5;241m==\u001b[39m cpx_code:\n\u001b[1;32m   2083\u001b[0m     \u001b[38;5;66;03m# multiobjective error but there IS a solution (?)\u001b[39;00m\n\u001b[1;32m   2084\u001b[0m     cpx_status \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1300\u001b[39m\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/docplex/mp/model.py:1099\u001b[0m, in \u001b[0;36mModel.fatal_ce_limits\u001b[0;34m(self, *args)\u001b[0m\n\u001b[1;32m   1096\u001b[0m nb_vars \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mnumber_of_variables\n\u001b[1;32m   1097\u001b[0m nb_constraints \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mnumber_of_constraints\n\u001b[0;32m-> 1099\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_error_handler\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfatal_limits_exceeded\u001b[49m\u001b[43m(\u001b[49m\u001b[43mnb_vars\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mnb_constraints\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/docplex/mp/error_handler.py:214\u001b[0m, in \u001b[0;36mAbstractErrorHandler.fatal_limits_exceeded\u001b[0;34m(self, nb_vars, nb_constraints)\u001b[0m\n\u001b[1;32m    212\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21mfatal_limits_exceeded\u001b[39m(\u001b[38;5;28mself\u001b[39m, nb_vars, nb_constraints):\n\u001b[1;32m    213\u001b[0m     docplex_error_stop_here()\n\u001b[0;32m--> 214\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m DOcplexLimitsExceeded(nb_vars, nb_constraints)\n",
      "\u001b[0;31mDOcplexLimitsExceeded\u001b[0m: **** Promotional version. Problem size limits (1000 vars, 1000 consts) exceeded, model has 1406 vars, 718 consts, CPLEX code=1016"
     ]
    }
   ],
   "source": [
    "from docplex.mp.model import Model\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "def train_model(X, y, h=1, m_=1):\n",
    "    n, m = X.shape\n",
    "    # --- Initialisation du modèle ---\n",
    "    mdl = Model(name=\"CreditClassification\")\n",
    "    \n",
    "    # Variables\n",
    "    w = mdl.continuous_var_list(m, name=\"w\")  # Coefficients\n",
    "    k = mdl.continuous_var(name=\"k\")          # Constante\n",
    "    E = mdl.continuous_var_list(n, lb=0, name=\"E\")  # Écarts externes\n",
    "    I = mdl.continuous_var_list(n, lb=0, name=\"I\")  # Écarts internes\n",
    "    \n",
    "    # Variables auxiliaires pour la valeur absolue\n",
    "    w_abs = mdl.continuous_var_list(m, lb=0, name=\"w_abs\")  # |w|\n",
    "    k_abs = mdl.continuous_var(lb=0, name=\"k_abs\")          # |k|\n",
    "    \n",
    "    # --- Fonction objectif ---\n",
    "    objective = mdl.sum(h * E[i] - m_ * I[i] for i in range(n))\n",
    "    mdl.minimize(objective)\n",
    "    \n",
    "    # --- Contraintes de discrimination ---\n",
    "    for i in range(n):\n",
    "        xi = X[i]\n",
    "        if y[i] == 1:  # G1\n",
    "            mdl.add_constraint(mdl.sum(w[j] * xi[j] for j in range(m)) + E[i] == k)\n",
    "        else:          # G2\n",
    "            mdl.add_constraint(mdl.sum(w[j] * xi[j] for j in range(m)) - E[i] + I[i] == k)\n",
    "    \n",
    "    # --- Contraintes pour la valeur absolue ---\n",
    "    for j in range(m):\n",
    "        mdl.add_constraint(w_abs[j] >= w[j])\n",
    "        mdl.add_constraint(w_abs[j] >= -w[j])\n",
    "    mdl.add_constraint(k_abs >= k)\n",
    "    mdl.add_constraint(k_abs >= -k)\n",
    "    \n",
    "    # --- Contrainte de normalisation ---\n",
    "    mdl.add_constraint(mdl.sum(w_abs[j] for j in range(m)) + k_abs == 1)\n",
    "    \n",
    "    # --- Résolution ---\n",
    "    solution = mdl.solve(log_output=True)\n",
    "    \n",
    "    if solution:\n",
    "        w_values = [w[j].solution_value for j in range(m)]\n",
    "        k_value = k.solution_value\n",
    "        obj_value = solution.objective_value\n",
    "        return w_values, k_value, obj_value\n",
    "    return None\n",
    "\n",
    "# Chargement des données Australian\n",
    "df_australian = pd.read_csv(\"/Users/mac/Documents/S4 et S3 de INSEA /devoir_1_MO/Australian.txt\", sep=\",\")\n",
    "X_australian = df_australian.iloc[:, :-1].values\n",
    "y_australian = df_australian.iloc[:, -1].values\n",
    "y_australian = np.where(y_australian == 0, -1, 1)  # Convertir 0 en -1\n",
    "\n",
    "# Chargement des données German\n",
    "df_german = pd.read_csv(\"/Users/mac/Documents/S4 et S3 de INSEA /devoir_1_MO/german.data-numeric.txt\", \n",
    "                       sep='\\s+',  # Use whitespace as separator\n",
    "                       header=None)  # No header in the file\n",
    "\n",
    "# Print data information\n",
    "print(\"German dataset shape:\", df_german.shape)\n",
    "print(\"\\nFirst few rows of German data:\")\n",
    "print(df_german.head())\n",
    "\n",
    "# Prepare features and target\n",
    "X_german = df_german.iloc[:, :-1].values  # All columns except the last one\n",
    "y_german = df_german.iloc[:, -1].values   # Last column is the target\n",
    "y_german = np.where(y_german == 2, -1, 1)  # Convert 2 to -1 and 1 stays 1\n",
    "\n",
    "# Test sur les données Australian\n",
    "print(\"\\n=== Résultats sur données Australian ===\")\n",
    "result_australian = train_model(X_australian, y_australian)\n",
    "if result_australian:\n",
    "    w, k, obj = result_australian\n",
    "    print(\"w =\", w)\n",
    "    print(\"k =\", k)\n",
    "    print(\"Valeur objectif =\", obj)\n",
    "\n",
    "# Test sur les données German\n",
    "print(\"\\n=== Résultats sur données German ===\")\n",
    "result_german = train_model(X_german, y_german)\n",
    "if result_german:\n",
    "    w, k, obj = result_german\n",
    "    print(\"w =\", w)\n",
    "    print(\"k =\", k)\n",
    "    print(\"Valeur objectif =\", obj)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
